import mongoose from "mongoose";
import dotenv from "dotenv";
import { Transaction } from "./src/models/Transaction.js";
import { Bank } from "./src/models/Bank.js";

dotenv.config();

const MONGO_URI = process.env.MONGO_URI || "mongodb://localhost:27017/expense-tracker";

async function migrate() {
  await mongoose.connect(MONGO_URI);
  console.log("Connected to DB");

  const transferTxns = await Transaction.find({ type: "transfer" });
  console.log(`Found ${transferTxns.length} transfer transactions`);

  let updated = 0;
  let skipped = 0;

  for (const txn of transferTxns) {
    try {
      let newNote = null;
      let newBankId = txn.bankId; // default: keep existing

      if (txn.transferType === "bank_to_cash") {
        if (!txn.fromBankId) { skipped++; continue; }
        const fromBank = await Bank.findById(txn.fromBankId);
        if (!fromBank) { skipped++; continue; }
        newNote = `₹${txn.amount} withdrawn from ${fromBank.bankName} to Cash`;
        newBankId = txn.fromBankId;
      }

      if (txn.transferType === "cash_to_bank") {
        if (!txn.toBankId) { skipped++; continue; }
        const toBank = await Bank.findById(txn.toBankId);
        if (!toBank) { skipped++; continue; }
        newNote = `₹${txn.amount} deposited to ${toBank.bankName} from Cash`;
        newBankId = txn.toBankId;
      }

      if (txn.transferType === "bank_to_bank") {
        if (!txn.fromBankId || !txn.toBankId) { skipped++; continue; }
        const fromBank = await Bank.findById(txn.fromBankId);
        const toBank = await Bank.findById(txn.toBankId);
        if (!fromBank || !toBank) { skipped++; continue; }
        newNote = `₹${txn.amount} transferred from ${fromBank.bankName} to ${toBank.bankName}`;
        newBankId = txn.toBankId;
      }

      if (!newNote) { skipped++; continue; }

      // don't overwrite if user already wrote a custom note manually before this migration
      // (comment out this check if you want to force-overwrite ALL transfer notes)
      const looksAutoGenerated =
        !txn.note ||
        txn.note === "-" ||
        /^₹.*(withdrawn|deposited|transferred)/.test(txn.note);

      if (!looksAutoGenerated) {
        console.log(`Skipping txn ${txn._id} — has custom note: "${txn.note}"`);
        skipped++;
        continue;
      }

      txn.note = newNote;
      txn.bankId = newBankId;
      await txn.save();
      updated++;
    } catch (err) {
      console.error(`Failed on txn ${txn._id}:`, err.message);
      skipped++;
    }
  }

  console.log(`Done. Updated: ${updated}, Skipped: ${skipped}`);
  await mongoose.disconnect();
}

migrate().catch((err) => {
  console.error("Migration failed:", err);
  process.exit(1);
});